### ISSUE TITLE
Navbar y footer

### ISSUE THREAD

**Issue by Lautidelamano** [Lautidelamano/Tienda-de-deporte#1]
Navbar:
Crear estructura menu principal
Contenido: Inicio, Categorias (Niños, Hombre y Mujer) y Contacto

Footer:
Contenido: Redes sociales, contacto, copyr

**Comment by mario-r-aguilar** [comment]
Ya subí mi rama donde está integrado el navbar, el footer y el botón de contraste con el script correspondiente para que puedan usarlo en sus secciones a desarrollar
